#!/bin/bash
trap ctrl-c INT

function ctrl-c() {
echo "Trap Ctrl C and exit"
exit
}

while [ 1 ]
do

timeout $1 bash <<EOT
  /usr/bin/killall -q  xv
  /usr/bin/killall -q java
  /usr/local/i3/usbreset.sh
  /usr/local/i3/jl-simple auto-run
EOT

done
