#!/bin/bash

function execute()
{
	touch $lockfile
	$1 
	rm $lockfile
}

timeout=$2
lockfile=$(echo $1 |cut -f1 -d".")
lockfile=".$lockfile.lck"
if [ -f $lockfile ]
then
	modify=$(stat $lockfile | grep Modify)
	dateString_date=$(echo $modify | awk '{print $2}')
	dateString_time=$(echo $modify | awk '{print $3}')
	currentDate=$(date +%s)
	fileDate=$(date --date="$dateString_date $dateString_time" +%s) 
	elapsed=$(($currentDate-$fileDate))
	if [[ elapsed -gt $timeout ]]
	then
		execute $1
	fi
else
	execute $1
fi
